name: Update Menu

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch:

jobs:
  update-menu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install specific version of Google Chrome
      run: |
       sudo dpkg -i chrome_114_amd64.deb
       sudo apt-get -f install  # 이건 dependency 문제를 자동으로 해결해 줘

    - name: 설정 정보 추가
      run: |
        git config --local user.email "ch445566@naver.com"
        git config --local user.name "lovebubbly"
   
    

    - name: Setup ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | awk '{ print $3 }' | cut -d'.' -f1)
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        if [[ "$DRIVER_VERSION" == *"<Error>"* ]]; then
          DRIVER_VERSION="114.0.5735.90"  # Fallback 버전
        fi
        wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip -o chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install selenium beautifulsoup4 requests

    - name: Update menu
      run: python hello.py


    - name: Commit and push changes
      run: |
        git config --local user.email "ch445566@naver.com"
        git config --local user.name "lovebubbly"
        git add -A :!chromedriver_linux64.zip
        git add .
        git commit -m "자동으로 파일 추가 및 수정 커밋"
        git push https://username:${{ secrets.MY_GITHUB_ACCESS_TOKEN }}@github.com/lovebubbly/haksik.git
      env:
        ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}


